#!/bin/bash

{
  echo -e "\033[33m🐶  Checking tests before pushing with Husky...\033[0m" &&
  npm run test &&
  echo -e "\033[33m🐶  ✓ Tests run well, we can push...\033[0m"
} || {
  echo -e "\033[33m🐶  ✗ Tests are failing, please fix them before pushing.\033[0m"
  exit 1
}
